# Generated by Django 3.1.6 on 2021-09-08 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='earned_scores',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
