# Generated by Django 3.1.6 on 2021-09-08 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20210908_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='earned_scores',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='UserPoints',
        ),
    ]
