# Generated by Django 3.1.6 on 2021-09-08 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20210905_0107'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
